services:
  redis:
    image: redis:8
    container_name: echo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass 123

volumes:
  redis-data: